version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - nmap_data:/app/instance
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - NMAP_PATH=nmap

volumes:
  nmap_data:
